version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - data:/mosquitto/data:rw
      - log:/mosquitto/log:rw
    ports:
      - "1883:1883"
      - "9001:9001"

volumes:
  data:
  log:
